- hosts: localhost
  tasks:
    - name: Check for ansible-galaxy install
      command: which ansible-galaxy
      failed_when: false
      register: register_ansible_galaxy

    - name: Set ansible_galaxy_executable
      set_fact:
        ansible_galaxy_executable: "{{ register_ansible_galaxy.stdout }}"

    # TODO(pabelanger): Move into own role.
    - name: Login into Ansible Galaxy with github token
      command: "{{ ansible_galaxy_executable }} -s {{ galaxy_info.server }} login --github-token {{ galaxy_info.token }}"
      no_log: True

    - name: Import role into Ansible Galaxy
      command: "{{ ansible_galaxy_executable }} -s {{ galaxy_info.server }} import --branch {{ zuul.branch }} {{ zuul.project['name'].split('/')[0] }} {{ zuul.project['short_name'] }}"
