- hosts: localhost
  tasks:
    - name: Ensure tox is installed
      shell: pip install --user tox

    - name: Bootstrap tox environment
      args:
        chdir: "{{ zuul.executor.work_root }}/{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}"
      shell: ~/.local/bin/tox -evenv --notest

    - name: Setup tweetrc credentials
      copy:
        content: "{{ twitter_ansible_network.credentials }}"
        dest: ~/.tweetrc

    - name: Send twitter announcement
      args:
        chdir: "{{ zuul.executor.work_root }}/{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}"
      shell: ".tox/venv/bin/python tools/twitter-announcement.py '{{ zuul.project.short_name }} {{ zuul.tag }} https://galaxy.ansible.com/{{ zuul.project.name }}'"
