# NOTE(pabelanger): We setup a fact here because the login task below is setup
# to use no_log. This gives the user some help debug info when troubleshooting
# the login command.
- name: Set _ansible_galaxy_command
  set_fact:
    _ansible_galaxy_command: "{{ ansible_galaxy_executable }} -s {{ ansible_galaxy_server }} "

- name: Login into Ansible Galaxy
  command: "{{ _ansible_galaxy_command }} login --github-token {{ ansible_galaxy_info.token }}"
  no_log: True

- name: Import role into Ansible Galaxy
  command: "{{ _ansible_galaxy_command }} import --branch {{ ansible_galaxy_branch }} {{ zuul.project['name'].split('/')[0] }} {{ zuul.project['short_name'] }}"
