---
- hosts: localhost
  tasks:
    - name: Run ara-report role
      include_role:
        name: ara-report

    - name: Run htmlify-logs role
      include_role:
        name: htmlify-logs

    - block:
      - name: Run upload-logs-swift role
        include_role:
          name: upload-logs-swift
        vars:
          zuul_log_cloud_config: "{{ vexxhost_clouds_yaml }}"
          zuul_log_partition: True
      ignore_errors: True
