- hosts: localhost
  tasks:
    - name: Run emit-job-header role
      include_role:
        name: emit-job-header
      vars:
        zuul_log_url: http://ansible-network.softwarefactory-project.io/logs/an

    - name: Run log-inventory role
      include_role:
        name: log-inventory

- hosts: all
  tasks:
    - name: Run start-zuul-console role
      include_role:
        name: start-zuul-console
